### PR TITLE
Livewire filter

### LINKED ISSUE #18: Create livewire filter above the projects:
Filter based on type project (digitale werkplaats, extern project 
Filter based on tags
Filter based on duration in sprints ( to be developed )

### PR DESCRIPTION
**Pull request by MoosMas**
Fixes #18 

Added filtering for projects

## ! Tags are case sensitive!
When adding tags to a project, be sure to pay attention to your capitalization. Wrong capitalization causes the filters to ignore the project.
For example, tag capitalization should be: HTML, PHP, C#, Backend, Frontend.

Related issues:
https://github.com/spatie/laravel-tags/issues/341
https://github.com/spatie/laravel-tags/issues/45
https://github.com/spatie/laravel-tags/issues/37

### CODE REVIEW

**Comment by Feddman** [comment]
Can you think of a way to ignore the capitalization? maybe use strtolower or other php functions to always check for the uncapitalized version?

**Comment by MoosMas** [comment]
You could search by the tag slug Spatie creates, but it doesn't have a built-in function to do this. The issues I linked discuss this but I haven't been able to implement it.

There are 2 other solutions I can think of:
- Upon tag creation, convert it to lowercase and store it in the database (like you mentioned)
- Create the tags beforehand and only let users select those tags (maybe using [Select2](https://select2.org/tagging))

If you prefer any of the above solutions, you can let me know and I'll see what I can do.

**Comment by Feddman** [comment]
Easiest solution would be creating tags beforehand then I guess!

**Comment by MoosMas** [comment]
I'll have a look and will create a new pull request when I get it to work. Backup plan will be converting tags to lowercase upon creation

**Pull request closed without merging**
